export default () => ({
  appName: 'saec project',
  appPort: parseInt(process.env.APPLICATION_PORT),
  jwtAccessSecret: process.env.APP_JWT_ACCESS_SECRET,
  jwtAccessExpiresTime: process.env.APP_JWT_ACCESS_EXPIRE_TIME,
  jwtRefreshSecret: process.env.APP_JWT_REFRESH_SECRET,
  jwtRefreshExpiresTime: process.env.APP_JWT_REFRESH_EXPIRE_TIME,
  jwt2FASecret: process.env.APP_JWT_2FA_SECRET,
  twoFATokenExpiresTime: process.env.APP_2FA_Token_EXPIRE_TIME,
  jwtEmailVerifySecret: process.env.APP_JWT_EMAIL_VERIFY_SECRET,
  jwtEmailVerifyExpiresTime: process.env.APP_JWT_EMAIL_VERIFY_EXPIRE_TIME,
  jwtResetSecret: process.env.APP_JWT_RESET_SECRET,
  jwtResetExpiresTime: process.env.APP_JWT_RESET_EXPIRE_TIME,
  dbURL: process.env.DATABASE_URL,
  mailHost: process.env.MAIL_HOST,
  mailPort: process.env.MAIL_PORT,
  mailPassword: process.env.MAIL_PASSWORD,
  mailUser: process.env.MAIL_USER,
  defaultMailFrom: 'saec@test.com',
  frontUrl: process.env.FRONT_URL,
});
